# .github/workflows/hola-actions.yml

name: Mi primer workflow

on:
  push:
    branches:
      - main

jobs:
  decir-hola:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar saludo
        run: echo "Hola GitHub Actions 🎉"
